/* Generated by Yosys 0.56+141 (git sha1 6b94376da, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module CSLA_CBL_2bit(A, B, Cin, Sum, Cout);
  input [1:0] A;
  wire [1:0] A;
  input [1:0] B;
  wire [1:0] B;
  input Cin;
  wire Cin;
  output [1:0] Sum;
  wire [1:0] Sum;
  output Cout;
  wire Cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  NAND2_X1 _07_ (
    .A1(A[1]),
    .A2(B[1]),
    .ZN(_06_)
  );
  AND2_X1 _08_ (
    .A1(A[0]),
    .A2(B[0]),
    .ZN(_00_)
  );
  OR2_X1 _09_ (
    .A1(A[0]),
    .A2(B[0]),
    .ZN(_01_)
  );
  XNOR2_X1 _10_ (
    .A(A[0]),
    .B(B[0]),
    .ZN(_02_)
  );
  AOI21_X1 _11_ (
    .A(_00_),
    .B1(_01_),
    .B2(Cin),
    .ZN(_03_)
  );
  NOR2_X1 _12_ (
    .A1(A[1]),
    .A2(B[1]),
    .ZN(_04_)
  );
  XOR2_X1 _13_ (
    .A(A[1]),
    .B(B[1]),
    .Z(_05_)
  );
  OAI21_X1 _14_ (
    .A(_06_),
    .B1(_03_),
    .B2(_04_),
    .ZN(Cout)
  );
  XNOR2_X1 _15_ (
    .A(Cin),
    .B(_02_),
    .ZN(Sum[0])
  );
  XNOR2_X1 _16_ (
    .A(_03_),
    .B(_05_),
    .ZN(Sum[1])
  );
endmodule

module CSLA_CBL_3bit(A, B, Cin, Sum, Cout);
  input [2:0] A;
  wire [2:0] A;
  input [2:0] B;
  wire [2:0] B;
  input Cin;
  wire Cin;
  output [2:0] Sum;
  wire [2:0] Sum;
  output Cout;
  wire Cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  INV_X1 _12_ (
    .A(Cin),
    .ZN(_00_)
  );
  NAND2_X1 _13_ (
    .A1(A[2]),
    .A2(B[2]),
    .ZN(_01_)
  );
  AND2_X1 _14_ (
    .A1(A[1]),
    .A2(B[1]),
    .ZN(_02_)
  );
  NAND2_X1 _15_ (
    .A1(A[0]),
    .A2(B[0]),
    .ZN(_03_)
  );
  NOR2_X1 _16_ (
    .A1(A[0]),
    .A2(B[0]),
    .ZN(_04_)
  );
  XOR2_X1 _17_ (
    .A(A[0]),
    .B(B[0]),
    .Z(_05_)
  );
  OAI21_X1 _18_ (
    .A(_03_),
    .B1(_04_),
    .B2(_00_),
    .ZN(_06_)
  );
  OR2_X1 _19_ (
    .A1(A[1]),
    .A2(B[1]),
    .ZN(_07_)
  );
  XNOR2_X1 _20_ (
    .A(A[1]),
    .B(B[1]),
    .ZN(_08_)
  );
  AOI21_X1 _21_ (
    .A(_02_),
    .B1(_06_),
    .B2(_07_),
    .ZN(_09_)
  );
  NOR2_X1 _22_ (
    .A1(A[2]),
    .A2(B[2]),
    .ZN(_10_)
  );
  XOR2_X1 _23_ (
    .A(A[2]),
    .B(B[2]),
    .Z(_11_)
  );
  OAI21_X1 _24_ (
    .A(_01_),
    .B1(_09_),
    .B2(_10_),
    .ZN(Cout)
  );
  XNOR2_X1 _25_ (
    .A(_00_),
    .B(_05_),
    .ZN(Sum[0])
  );
  XNOR2_X1 _26_ (
    .A(_06_),
    .B(_08_),
    .ZN(Sum[1])
  );
  XNOR2_X1 _27_ (
    .A(_09_),
    .B(_11_),
    .ZN(Sum[2])
  );
endmodule

module SQRT_CSLA_CBL_8bit(A, B, Cin, Sum, Cout);
  input [7:0] A;
  wire [7:0] A;
  input [7:0] B;
  wire [7:0] B;
  input Cin;
  wire Cin;
  output [7:0] Sum;
  wire [7:0] Sum;
  output Cout;
  wire Cout;
  wire C1;
  wire C2;
  CSLA_CBL_2bit U0 (
    .A(A[1:0]),
    .B(B[1:0]),
    .Cin(Cin),
    .Cout(C1),
    .Sum(Sum[1:0])
  );
  CSLA_CBL_3bit U1 (
    .A(A[4:2]),
    .B(B[4:2]),
    .Cin(C1),
    .Cout(C2),
    .Sum(Sum[4:2])
  );
  CSLA_CBL_3bit U2 (
    .A(A[7:5]),
    .B(B[7:5]),
    .Cin(C2),
    .Cout(Cout),
    .Sum(Sum[7:5])
  );
endmodule

module four_bit_ripple_adder(g, h, carryin, summation, carryout);
  input [3:0] g;
  wire [3:0] g;
  input [3:0] h;
  wire [3:0] h;
  input carryin;
  wire carryin;
  output [3:0] summation;
  wire [3:0] summation;
  output carryout;
  wire carryout;
  wire c0;
  wire c1;
  wire c2;
  full_adder f1 (
    .cin(carryin),
    .cout(c0),
    .e(g[0]),
    .f(h[0]),
    .sum(summation[0])
  );
  full_adder f2 (
    .cin(c0),
    .cout(c1),
    .e(g[1]),
    .f(h[1]),
    .sum(summation[1])
  );
  full_adder f3 (
    .cin(c1),
    .cout(c2),
    .e(g[2]),
    .f(h[2]),
    .sum(summation[2])
  );
  full_adder f4 (
    .cin(c2),
    .cout(carryout),
    .e(g[3]),
    .f(h[3]),
    .sum(summation[3])
  );
endmodule

module full_adder(e, f, cin, sum, cout);
  input e;
  wire e;
  input f;
  wire f;
  input cin;
  wire cin;
  output sum;
  wire sum;
  output cout;
  wire cout;
  wire _0_;
  wire _1_;
  wire _2_;
  NAND2_X1 _3_ (
    .A1(e),
    .A2(cin),
    .ZN(_0_)
  );
  XNOR2_X1 _4_ (
    .A(e),
    .B(cin),
    .ZN(_1_)
  );
  XNOR2_X1 _5_ (
    .A(f),
    .B(_1_),
    .ZN(sum)
  );
  OAI21_X1 _6_ (
    .A(f),
    .B1(cin),
    .B2(e),
    .ZN(_2_)
  );
  NAND2_X1 _7_ (
    .A1(_0_),
    .A2(_2_),
    .ZN(cout)
  );
endmodule

module half_adder(x, y, sum, cout);
  input x;
  wire x;
  input y;
  wire y;
  output sum;
  wire sum;
  output cout;
  wire cout;
  AND2_X1 _0_ (
    .A1(x),
    .A2(y),
    .ZN(cout)
  );
  XOR2_X1 _1_ (
    .A(x),
    .B(y),
    .Z(sum)
  );
endmodule

module vedic_eight_pipeline(i, j, z, clk1);
  input [7:0] i;
  wire [7:0] i;
  input [7:0] j;
  wire [7:0] j;
  output [15:0] z;
  wire [15:0] z;
  input clk1;
  wire clk1;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire [7:0] L12_w_1;
  wire [7:0] L12_w_2;
  wire [7:0] L12_w_3;
  wire [7:0] L12_w_4;
  wire L23_carry_0;
  wire [7:0] L23_s_1;
  wire [7:0] L23_w_1;
  wire [7:0] L23_w_4;
  wire L34_carry_0;
  wire L34_carry_1;
  wire [7:0] L34_s_2;
  wire [7:0] L34_w_1;
  wire [7:0] L34_w_4;
  wire [7:0] L45_s_2;
  wire [7:0] L45_s_3;
  wire [7:0] L45_w_1;
  wire carry_0;
  wire carry_1;
  wire carry_2;
  wire [7:0] s_1;
  wire [7:0] s_2;
  wire [7:0] s_3;
  wire [7:0] w_1;
  wire [7:0] w_2;
  wire [7:0] w_3;
  wire [7:0] w_4;
  DFF_X1 _111_ (
    .CK(clk1),
    .D(L34_s_2[0]),
    .Q(L45_s_2[0]),
    .QN(_001_)
  );
  DFF_X1 _112_ (
    .CK(clk1),
    .D(L34_s_2[1]),
    .Q(L45_s_2[1]),
    .QN(_002_)
  );
  DFF_X1 _113_ (
    .CK(clk1),
    .D(L34_s_2[2]),
    .Q(L45_s_2[2]),
    .QN(_003_)
  );
  DFF_X1 _114_ (
    .CK(clk1),
    .D(L34_s_2[3]),
    .Q(L45_s_2[3]),
    .QN(_004_)
  );
  DFF_X1 _115_ (
    .CK(clk1),
    .D(L34_w_1[0]),
    .Q(L45_w_1[0]),
    .QN(_005_)
  );
  DFF_X1 _116_ (
    .CK(clk1),
    .D(L34_w_1[1]),
    .Q(L45_w_1[1]),
    .QN(_006_)
  );
  DFF_X1 _117_ (
    .CK(clk1),
    .D(L34_w_1[2]),
    .Q(L45_w_1[2]),
    .QN(_007_)
  );
  DFF_X1 _118_ (
    .CK(clk1),
    .D(L34_w_1[3]),
    .Q(L45_w_1[3]),
    .QN(_008_)
  );
  DFF_X1 _119_ (
    .CK(clk1),
    .D(s_3[0]),
    .Q(L45_s_3[0]),
    .QN(_009_)
  );
  DFF_X1 _120_ (
    .CK(clk1),
    .D(s_3[1]),
    .Q(L45_s_3[1]),
    .QN(_010_)
  );
  DFF_X1 _121_ (
    .CK(clk1),
    .D(s_3[2]),
    .Q(L45_s_3[2]),
    .QN(_011_)
  );
  DFF_X1 _122_ (
    .CK(clk1),
    .D(s_3[3]),
    .Q(L45_s_3[3]),
    .QN(_012_)
  );
  DFF_X1 _123_ (
    .CK(clk1),
    .D(s_3[4]),
    .Q(L45_s_3[4]),
    .QN(_013_)
  );
  DFF_X1 _124_ (
    .CK(clk1),
    .D(s_3[5]),
    .Q(L45_s_3[5]),
    .QN(_014_)
  );
  DFF_X1 _125_ (
    .CK(clk1),
    .D(s_3[6]),
    .Q(L45_s_3[6]),
    .QN(_015_)
  );
  DFF_X1 _126_ (
    .CK(clk1),
    .D(s_3[7]),
    .Q(L45_s_3[7]),
    .QN(_016_)
  );
  DFF_X1 _127_ (
    .CK(clk1),
    .D(L45_w_1[0]),
    .Q(z[0]),
    .QN(_017_)
  );
  DFF_X1 _128_ (
    .CK(clk1),
    .D(L45_w_1[1]),
    .Q(z[1]),
    .QN(_018_)
  );
  DFF_X1 _129_ (
    .CK(clk1),
    .D(L45_w_1[2]),
    .Q(z[2]),
    .QN(_019_)
  );
  DFF_X1 _130_ (
    .CK(clk1),
    .D(L45_w_1[3]),
    .Q(z[3]),
    .QN(_020_)
  );
  DFF_X1 _131_ (
    .CK(clk1),
    .D(L45_s_2[0]),
    .Q(z[4]),
    .QN(_021_)
  );
  DFF_X1 _132_ (
    .CK(clk1),
    .D(L45_s_2[1]),
    .Q(z[5]),
    .QN(_022_)
  );
  DFF_X1 _133_ (
    .CK(clk1),
    .D(L45_s_2[2]),
    .Q(z[6]),
    .QN(_023_)
  );
  DFF_X1 _134_ (
    .CK(clk1),
    .D(L45_s_2[3]),
    .Q(z[7]),
    .QN(_024_)
  );
  DFF_X1 _135_ (
    .CK(clk1),
    .D(L45_s_3[0]),
    .Q(z[8]),
    .QN(_025_)
  );
  DFF_X1 _136_ (
    .CK(clk1),
    .D(L45_s_3[1]),
    .Q(z[9]),
    .QN(_026_)
  );
  DFF_X1 _137_ (
    .CK(clk1),
    .D(L45_s_3[2]),
    .Q(z[10]),
    .QN(_027_)
  );
  DFF_X1 _138_ (
    .CK(clk1),
    .D(L45_s_3[3]),
    .Q(z[11]),
    .QN(_028_)
  );
  DFF_X1 _139_ (
    .CK(clk1),
    .D(L45_s_3[4]),
    .Q(z[12]),
    .QN(_029_)
  );
  DFF_X1 _140_ (
    .CK(clk1),
    .D(L45_s_3[5]),
    .Q(z[13]),
    .QN(_030_)
  );
  DFF_X1 _141_ (
    .CK(clk1),
    .D(L45_s_3[6]),
    .Q(z[14]),
    .QN(_031_)
  );
  DFF_X1 _142_ (
    .CK(clk1),
    .D(L45_s_3[7]),
    .Q(z[15]),
    .QN(_032_)
  );
  DFF_X1 _143_ (
    .CK(clk1),
    .D(s_2[0]),
    .Q(L34_s_2[0]),
    .QN(_033_)
  );
  DFF_X1 _144_ (
    .CK(clk1),
    .D(s_2[1]),
    .Q(L34_s_2[1]),
    .QN(_034_)
  );
  DFF_X1 _145_ (
    .CK(clk1),
    .D(s_2[2]),
    .Q(L34_s_2[2]),
    .QN(_035_)
  );
  DFF_X1 _146_ (
    .CK(clk1),
    .D(s_2[3]),
    .Q(L34_s_2[3]),
    .QN(_036_)
  );
  DFF_X1 _147_ (
    .CK(clk1),
    .D(s_2[4]),
    .Q(L34_s_2[4]),
    .QN(_037_)
  );
  DFF_X1 _148_ (
    .CK(clk1),
    .D(s_2[5]),
    .Q(L34_s_2[5]),
    .QN(_038_)
  );
  DFF_X1 _149_ (
    .CK(clk1),
    .D(s_2[6]),
    .Q(L34_s_2[6]),
    .QN(_039_)
  );
  DFF_X1 _150_ (
    .CK(clk1),
    .D(s_2[7]),
    .Q(L34_s_2[7]),
    .QN(_040_)
  );
  DFF_X1 _151_ (
    .CK(clk1),
    .D(w_4[0]),
    .Q(L12_w_4[0]),
    .QN(_041_)
  );
  DFF_X1 _152_ (
    .CK(clk1),
    .D(w_4[1]),
    .Q(L12_w_4[1]),
    .QN(_042_)
  );
  DFF_X1 _153_ (
    .CK(clk1),
    .D(w_4[2]),
    .Q(L12_w_4[2]),
    .QN(_043_)
  );
  DFF_X1 _154_ (
    .CK(clk1),
    .D(w_4[3]),
    .Q(L12_w_4[3]),
    .QN(_044_)
  );
  DFF_X1 _155_ (
    .CK(clk1),
    .D(w_4[4]),
    .Q(L12_w_4[4]),
    .QN(_045_)
  );
  DFF_X1 _156_ (
    .CK(clk1),
    .D(w_4[5]),
    .Q(L12_w_4[5]),
    .QN(_046_)
  );
  DFF_X1 _157_ (
    .CK(clk1),
    .D(w_4[6]),
    .Q(L12_w_4[6]),
    .QN(_047_)
  );
  DFF_X1 _158_ (
    .CK(clk1),
    .D(w_4[7]),
    .Q(L12_w_4[7]),
    .QN(_048_)
  );
  DFF_X1 _159_ (
    .CK(clk1),
    .D(w_3[0]),
    .Q(L12_w_3[0]),
    .QN(_049_)
  );
  DFF_X1 _160_ (
    .CK(clk1),
    .D(w_3[1]),
    .Q(L12_w_3[1]),
    .QN(_050_)
  );
  DFF_X1 _161_ (
    .CK(clk1),
    .D(w_3[2]),
    .Q(L12_w_3[2]),
    .QN(_051_)
  );
  DFF_X1 _162_ (
    .CK(clk1),
    .D(w_3[3]),
    .Q(L12_w_3[3]),
    .QN(_052_)
  );
  DFF_X1 _163_ (
    .CK(clk1),
    .D(w_3[4]),
    .Q(L12_w_3[4]),
    .QN(_053_)
  );
  DFF_X1 _164_ (
    .CK(clk1),
    .D(w_3[5]),
    .Q(L12_w_3[5]),
    .QN(_054_)
  );
  DFF_X1 _165_ (
    .CK(clk1),
    .D(w_3[6]),
    .Q(L12_w_3[6]),
    .QN(_055_)
  );
  DFF_X1 _166_ (
    .CK(clk1),
    .D(w_3[7]),
    .Q(L12_w_3[7]),
    .QN(_056_)
  );
  DFF_X1 _167_ (
    .CK(clk1),
    .D(w_2[0]),
    .Q(L12_w_2[0]),
    .QN(_057_)
  );
  DFF_X1 _168_ (
    .CK(clk1),
    .D(w_2[1]),
    .Q(L12_w_2[1]),
    .QN(_058_)
  );
  DFF_X1 _169_ (
    .CK(clk1),
    .D(w_2[2]),
    .Q(L12_w_2[2]),
    .QN(_059_)
  );
  DFF_X1 _170_ (
    .CK(clk1),
    .D(w_2[3]),
    .Q(L12_w_2[3]),
    .QN(_060_)
  );
  DFF_X1 _171_ (
    .CK(clk1),
    .D(w_2[4]),
    .Q(L12_w_2[4]),
    .QN(_061_)
  );
  DFF_X1 _172_ (
    .CK(clk1),
    .D(w_2[5]),
    .Q(L12_w_2[5]),
    .QN(_062_)
  );
  DFF_X1 _173_ (
    .CK(clk1),
    .D(w_2[6]),
    .Q(L12_w_2[6]),
    .QN(_063_)
  );
  DFF_X1 _174_ (
    .CK(clk1),
    .D(w_2[7]),
    .Q(L12_w_2[7]),
    .QN(_064_)
  );
  DFF_X1 _175_ (
    .CK(clk1),
    .D(w_1[0]),
    .Q(L12_w_1[0]),
    .QN(_065_)
  );
  DFF_X1 _176_ (
    .CK(clk1),
    .D(w_1[1]),
    .Q(L12_w_1[1]),
    .QN(_066_)
  );
  DFF_X1 _177_ (
    .CK(clk1),
    .D(w_1[2]),
    .Q(L12_w_1[2]),
    .QN(_067_)
  );
  DFF_X1 _178_ (
    .CK(clk1),
    .D(w_1[3]),
    .Q(L12_w_1[3]),
    .QN(_068_)
  );
  DFF_X1 _179_ (
    .CK(clk1),
    .D(w_1[4]),
    .Q(L12_w_1[4]),
    .QN(_069_)
  );
  DFF_X1 _180_ (
    .CK(clk1),
    .D(w_1[5]),
    .Q(L12_w_1[5]),
    .QN(_070_)
  );
  DFF_X1 _181_ (
    .CK(clk1),
    .D(w_1[6]),
    .Q(L12_w_1[6]),
    .QN(_071_)
  );
  DFF_X1 _182_ (
    .CK(clk1),
    .D(w_1[7]),
    .Q(L12_w_1[7]),
    .QN(_072_)
  );
  DFF_X1 _183_ (
    .CK(clk1),
    .D(carry_0),
    .Q(L23_carry_0),
    .QN(_073_)
  );
  DFF_X1 _184_ (
    .CK(clk1),
    .D(L12_w_4[0]),
    .Q(L23_w_4[0]),
    .QN(_074_)
  );
  DFF_X1 _185_ (
    .CK(clk1),
    .D(L12_w_4[1]),
    .Q(L23_w_4[1]),
    .QN(_075_)
  );
  DFF_X1 _186_ (
    .CK(clk1),
    .D(L12_w_4[2]),
    .Q(L23_w_4[2]),
    .QN(_076_)
  );
  DFF_X1 _187_ (
    .CK(clk1),
    .D(L12_w_4[3]),
    .Q(L23_w_4[3]),
    .QN(_077_)
  );
  DFF_X1 _188_ (
    .CK(clk1),
    .D(L12_w_4[4]),
    .Q(L23_w_4[4]),
    .QN(_078_)
  );
  DFF_X1 _189_ (
    .CK(clk1),
    .D(L12_w_4[5]),
    .Q(L23_w_4[5]),
    .QN(_079_)
  );
  DFF_X1 _190_ (
    .CK(clk1),
    .D(L12_w_4[6]),
    .Q(L23_w_4[6]),
    .QN(_080_)
  );
  DFF_X1 _191_ (
    .CK(clk1),
    .D(L12_w_4[7]),
    .Q(L23_w_4[7]),
    .QN(_081_)
  );
  DFF_X1 _192_ (
    .CK(clk1),
    .D(s_1[0]),
    .Q(L23_s_1[0]),
    .QN(_082_)
  );
  DFF_X1 _193_ (
    .CK(clk1),
    .D(s_1[1]),
    .Q(L23_s_1[1]),
    .QN(_083_)
  );
  DFF_X1 _194_ (
    .CK(clk1),
    .D(s_1[2]),
    .Q(L23_s_1[2]),
    .QN(_084_)
  );
  DFF_X1 _195_ (
    .CK(clk1),
    .D(s_1[3]),
    .Q(L23_s_1[3]),
    .QN(_085_)
  );
  DFF_X1 _196_ (
    .CK(clk1),
    .D(s_1[4]),
    .Q(L23_s_1[4]),
    .QN(_086_)
  );
  DFF_X1 _197_ (
    .CK(clk1),
    .D(s_1[5]),
    .Q(L23_s_1[5]),
    .QN(_087_)
  );
  DFF_X1 _198_ (
    .CK(clk1),
    .D(s_1[6]),
    .Q(L23_s_1[6]),
    .QN(_088_)
  );
  DFF_X1 _199_ (
    .CK(clk1),
    .D(s_1[7]),
    .Q(L23_s_1[7]),
    .QN(_089_)
  );
  DFF_X1 _200_ (
    .CK(clk1),
    .D(L12_w_1[0]),
    .Q(L23_w_1[0]),
    .QN(_090_)
  );
  DFF_X1 _201_ (
    .CK(clk1),
    .D(L12_w_1[1]),
    .Q(L23_w_1[1]),
    .QN(_091_)
  );
  DFF_X1 _202_ (
    .CK(clk1),
    .D(L12_w_1[2]),
    .Q(L23_w_1[2]),
    .QN(_092_)
  );
  DFF_X1 _203_ (
    .CK(clk1),
    .D(L12_w_1[3]),
    .Q(L23_w_1[3]),
    .QN(_093_)
  );
  DFF_X1 _204_ (
    .CK(clk1),
    .D(L12_w_1[4]),
    .Q(L23_w_1[4]),
    .QN(_094_)
  );
  DFF_X1 _205_ (
    .CK(clk1),
    .D(L12_w_1[5]),
    .Q(L23_w_1[5]),
    .QN(_095_)
  );
  DFF_X1 _206_ (
    .CK(clk1),
    .D(L12_w_1[6]),
    .Q(L23_w_1[6]),
    .QN(_096_)
  );
  DFF_X1 _207_ (
    .CK(clk1),
    .D(L12_w_1[7]),
    .Q(L23_w_1[7]),
    .QN(_097_)
  );
  DFF_X1 _208_ (
    .CK(clk1),
    .D(carry_1),
    .Q(L34_carry_1),
    .QN(_098_)
  );
  DFF_X1 _209_ (
    .CK(clk1),
    .D(L23_carry_0),
    .Q(L34_carry_0),
    .QN(_099_)
  );
  DFF_X1 _210_ (
    .CK(clk1),
    .D(L23_w_4[0]),
    .Q(L34_w_4[0]),
    .QN(_100_)
  );
  DFF_X1 _211_ (
    .CK(clk1),
    .D(L23_w_4[1]),
    .Q(L34_w_4[1]),
    .QN(_101_)
  );
  DFF_X1 _212_ (
    .CK(clk1),
    .D(L23_w_4[2]),
    .Q(L34_w_4[2]),
    .QN(_102_)
  );
  DFF_X1 _213_ (
    .CK(clk1),
    .D(L23_w_4[3]),
    .Q(L34_w_4[3]),
    .QN(_103_)
  );
  DFF_X1 _214_ (
    .CK(clk1),
    .D(L23_w_4[4]),
    .Q(L34_w_4[4]),
    .QN(_104_)
  );
  DFF_X1 _215_ (
    .CK(clk1),
    .D(L23_w_4[5]),
    .Q(L34_w_4[5]),
    .QN(_105_)
  );
  DFF_X1 _216_ (
    .CK(clk1),
    .D(L23_w_4[6]),
    .Q(L34_w_4[6]),
    .QN(_106_)
  );
  DFF_X1 _217_ (
    .CK(clk1),
    .D(L23_w_4[7]),
    .Q(L34_w_4[7]),
    .QN(_107_)
  );
  DFF_X1 _218_ (
    .CK(clk1),
    .D(L23_w_1[0]),
    .Q(L34_w_1[0]),
    .QN(_108_)
  );
  DFF_X1 _219_ (
    .CK(clk1),
    .D(L23_w_1[1]),
    .Q(L34_w_1[1]),
    .QN(_109_)
  );
  DFF_X1 _220_ (
    .CK(clk1),
    .D(L23_w_1[2]),
    .Q(L34_w_1[2]),
    .QN(_110_)
  );
  DFF_X1 _221_ (
    .CK(clk1),
    .D(L23_w_1[3]),
    .Q(L34_w_1[3]),
    .QN(_000_)
  );
  SQRT_CSLA_CBL_8bit r_1 (
    .A(L12_w_2),
    .B(L12_w_3),
    .Cin(1'b0),
    .Cout(carry_0),
    .Sum(s_1)
  );
  SQRT_CSLA_CBL_8bit r_2 (
    .A({ 4'b0000, L23_w_1[7:4] }),
    .B(L23_s_1),
    .Cin(1'b0),
    .Cout(carry_1),
    .Sum(s_2)
  );
  SQRT_CSLA_CBL_8bit r_3 (
    .A(L34_w_4),
    .B({ 3'b000, L34_carry_0, L34_s_2[7:4] }),
    .Cin(L34_carry_1),
    .Cout(carry_2),
    .Sum(s_3)
  );
  vedic_four v1 (
    .q(w_1),
    .x(i[3:0]),
    .y(j[3:0])
  );
  vedic_four v2 (
    .q(w_2),
    .x(i[7:4]),
    .y(j[3:0])
  );
  vedic_four v3 (
    .q(w_3),
    .x(i[3:0]),
    .y(j[7:4])
  );
  vedic_four v4 (
    .q(w_4),
    .x(i[7:4]),
    .y(j[7:4])
  );
endmodule

module vedic_four(x, y, q);
  input [3:0] x;
  wire [3:0] x;
  input [3:0] y;
  wire [3:0] y;
  output [7:0] q;
  wire [7:0] q;
  wire carry0;
  wire carry1;
  wire carry2;
  wire carry_ha;
  wire [3:0] s1;
  wire [3:0] s2;
  wire [3:0] s3;
  wire sum_ha;
  wire [3:0] w1;
  wire [3:0] w2;
  wire [3:0] w3;
  wire [3:0] w4;
  half_adder h1 (
    .cout(carry_ha),
    .sum(sum_ha),
    .x(carry0),
    .y(carry1)
  );
  vedic_two m1 (
    .a(x[1:0]),
    .b(y[1:0]),
    .out(w1)
  );
  vedic_two m2 (
    .a(x[1:0]),
    .b(y[3:2]),
    .out(w2)
  );
  vedic_two m3 (
    .a(x[3:2]),
    .b(y[1:0]),
    .out(w3)
  );
  vedic_two m4 (
    .a(x[3:2]),
    .b(y[3:2]),
    .out(w4)
  );
  four_bit_ripple_adder r1 (
    .carryin(1'b0),
    .carryout(carry0),
    .g(w2),
    .h(w3),
    .summation(s1)
  );
  four_bit_ripple_adder r2 (
    .carryin(1'b0),
    .carryout(carry1),
    .g(s1),
    .h({ 2'b00, w1[3:2] }),
    .summation(s2)
  );
  four_bit_ripple_adder r3 (
    .carryin(1'b0),
    .carryout(carry2),
    .g(w4),
    .h({ carry_ha, sum_ha, s2[3:2] }),
    .summation(s3)
  );
  assign q = { s3, s2[1:0], w1[1:0] };
endmodule

module vedic_two(a, b, out);
  input [1:0] a;
  wire [1:0] a;
  input [1:0] b;
  wire [1:0] b;
  output [3:0] out;
  wire [3:0] out;
  wire cout1;
  wire cout2;
  wire sum;
  wire sum2;
  wire w1;
  wire w2;
  wire w3;
  wire w4;
  AND2_X1 _0_ (
    .A1(a[0]),
    .A2(b[0]),
    .ZN(w1)
  );
  AND2_X1 _1_ (
    .A1(b[0]),
    .A2(a[1]),
    .ZN(w2)
  );
  AND2_X1 _2_ (
    .A1(a[0]),
    .A2(b[1]),
    .ZN(w3)
  );
  AND2_X1 _3_ (
    .A1(a[1]),
    .A2(b[1]),
    .ZN(w4)
  );
  half_adder h1 (
    .cout(cout1),
    .sum(sum),
    .x(w2),
    .y(w3)
  );
  half_adder h2 (
    .cout(cout2),
    .sum(sum2),
    .x(w4),
    .y(cout1)
  );
  assign out = { cout2, sum2, sum, w1 };
endmodule
